fix: Missing dependency 'string-to-color' in package.json
I get this error running the web frontend:

✘ [ERROR] TS2307: Cannot find module 'string-to-color' or its corresponding type declarations. [plugin angular-compiler]

    src/app/components/chat/chat.component.ts:30:16:
      30 │ import stc from 'string-to-color';
         ╵                 ~~~~~~~~~~~~~~~~~